core/urls.py
from django.urls import path, re_path
from . import views

#from core.views import default_context

app_name = 'core'

urlpatterns = [
    path('', views.index, name="index"),
    path('game/new/', views.new_game, name="new_game"),
    path('game/<str:code>/', views.active_game, name="active_game"),
    path('game/<str:code>/details', views.game_details, name="game_details"),
]

dirtysanta/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('core.urls')),
    path('admin/', admin.site.urls),
]

core/models.py
from enum import unique
from typing import cast
from django.conf import settings
from django.db import models
import uuid

# Create your models here.

class GameSession(models.Model):
    code = models.CharField("Game Code", max_length=6, default=uuid.uuid4().hex[:6].upper(), unique=True, editable=False)
    manager = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    setup = models.BooleanField("Game Setup & Ready", default=False)
    ready = models.BooleanField("Ready To Start", default=False)
    current_turn = models.IntegerField("Current Players Turn", default=1)
    theif = models.ForeignKey("core.GamePlayer", verbose_name="Previous Theif", on_delete=models.CASCADE, default=None, blank=True, null=True)
    complete = models.BooleanField("Game Complete", default=False)
    created_date = models.DateTimeField(auto_now_add=True)
    completion_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.code

class GamePlayer(models.Model):
    session_id = models.ForeignKey("core.GameSession", verbose_name="Session ID", on_delete=models.CASCADE)
    name = models.CharField("Player Name", max_length=50)
    turn = models.SmallIntegerField("Players Turn Number", blank=True, null=True, default=None)
    possession = models.BooleanField("Player has gift", default=False)
    phone = models.BooleanField("Player using phone", default=False)

    def __str__(self):
        return self.name

core/views.py
from django.http import JsonResponse
from django.shortcuts import render, redirect

from core.models import GamePlayer, GameSession
import random
import uuid

# Create your views here.

def default_context():
    context = {
        'title': 'Dirty Santa',
    }
    return context


def index(request):
    def load_index(request, add_context=None):
        if request.user.is_authenticated:
            game = GameSession.objects.filter(manager=request.user, complete=False)
            if game.exists():
                game = GameSession.objects.get(manager=request.user, complete=False)
                cur_game = game.code
                cur_game_setup = game.setup
                cur_game_ready = game.ready
            else:
                cur_game = None
                cur_game_setup = None
                cur_game_ready = None
        else:
            if "game" in request.session:
                cur_game = request.session['game']
                cur_game_setup = None
                cur_game_ready = None
            else:
                cur_game = None
                cur_game_setup = None
                cur_game_ready = None


        context = {
            "current_game": cur_game,
            "cur_game_setup": cur_game_setup,
            "cur_game_ready": cur_game_ready,
        }
        context.update(default_context())
        if add_context != None:
            context.update(add_context)
        return render(request, "core/index.html", context)

    if request.POST:
        if "join" in request.POST:
            code = request.POST['join'].upper()
            if request.POST['name'] == "":
                return load_index(request, {'error':'You need to enter your name!', 'code': code})
            # check if code entered is correct
            game_exists = GameSession.objects.filter(code=code)
            if game_exists.exists():
                player = request.POST['name']
                # create session for player
                request.session['game'] = code
                request.session['player_name'] = player
                # add player to DB
                game = GameSession.objects.get(code=code)
                new_game_player = GamePlayer.objects.create(session_id=game, name=player, phone=True)
                request.session['player_id'] = new_game_player.id
                return redirect("core:active_game", code)
            else:
                return load_index(request, {'error':'Incorrect Code', 'code': code})
        elif "continue" in request.POST:
            code = request.POST['continue']
            game = GameSession.objects.get(code=code)
            player = GamePlayer.objects.get(session_id=game, name=request.user.username)
            request.session['game'] = game.code
            request.session['player_name'] = player.name
            request.session['player_id'] = player.id
            return redirect("core:active_game", code)
        elif "new" in request.POST:
            return redirect("core:new_game")
        elif "setup" in request.POST:
            return redirect("core:new_game")
        else:
            return load_index(request, {'error':'Error! Not sure what though...'})
    else:
        '''
        try:
            if request.session['game']:
                return redirect('core:active_game', request.session['game'])
        except KeyError:
            pass
        '''
        return load_index(request)


def new_game(request):
    check_game = GameSession.objects.filter(manager=request.user, complete=False)
    if check_game.exists():
        print("game exists!")
        game = GameSession.objects.get(manager=request.user, complete=False)
    else:
        code = uuid.uuid4().hex[:6].upper()
        game = GameSession.objects.create(manager=request.user, code=code)
        player = GamePlayer.objects.create(session_id=game, name=request.user.username)
        request.session['game'] = game.code
        request.session['player_name'] = player.name
        request.session['player_id'] = player.id

    # set new_game_player & new_game_player_outcome variable in case nothing posted
    new_game_player = None
    new_game_player_message = None
    new_game_player_outcome = None

    if request.method == "POST":
        if 'action' in request.POST:
            if request.POST['action'] == "setup":
                game = game_setup(game)
            if request.POST['action'] == "cancel":
                game = GameSession.objects.get(code=game)
                game.complete = True
                game.save()
                return redirect('core:index')
            elif request.POST['action'] == "ready":
                game_session = GameSession.objects.get(code=game)
                game_session.ready = True
                game_session.save()
                game = game_session
                return redirect('core:active_game', game.code)
            elif request.POST['action'] == "add_player":
                # add new player - not using phone
                game = GameSession.objects.get(code=game)
                if GamePlayer.objects.filter(session_id=game, name=request.POST['new_name']).exists():
                    new_game_player = request.POST['new_name']
                    new_game_player_message = "already exists."
                    new_game_player_outcome = "warning"
                else:
                    new_game_player = GamePlayer.objects.create(session_id=game, name=request.POST['new_name'])
                    new_game_player = new_game_player.name
                    new_game_player_message = "has been added."
                    new_game_player_outcome = "success"


    players = GamePlayer.objects.filter(session_id=game.id).order_by('turn', 'name')
    player_count = players.count()

    context = {
        "game": game,
        "players": players,
        "player_count": player_count,
        "new_player": new_game_player,
        "new_player_message": new_game_player_message,
        "new_player_outcome": new_game_player_outcome,
    }
    context.update(default_context())
    return render(request, "core/new_game.html", context)

def game_setup(game):
    players = GamePlayer.objects.filter(session_id=game)
    player_list = []
    for player in players:
        player_list.append(player.id)
    items = list(player_list)
    random.shuffle(items)
    random.shuffle(items)
    random.shuffle(items)
    turn = 1
    for value in items:
        player = GamePlayer.objects.get(id=value)
        player.turn = turn
        player.save()
        turn = turn + 1
    game_session = GameSession.objects.get(code=game)
    game_session.setup = True
    game_session.save()
    return game_session


def active_game(request, code):
    game = GameSession.objects.get(code=code)
    if game.complete == True:
        try:
            del request.session['game']
            del request.session['player_name']
            del request.session['player_id']
            del request.session['current_player']
            return redirect("core:index")
        except:
            return redirect("core:index")

    context = {
        "game": game,
        "session_id": request.session['player_id'],
    }


    if game.ready == True:
        players = GamePlayer.objects.filter(session_id=game).order_by('name')
        current_player = players.get(turn=game.current_turn)
        player_gifts = players.filter(possession=True)
        player_with_gifts = {}
        for player in player_gifts:
            player_with_gifts.update({player.id:player.name})

        if game.theif:
            theif = game.theif.id
        else:
            theif = None
        context.update({
            "current_player": {'id':current_player.id, 'name':current_player.name, 'phone':current_player.phone},
            "players_with_gifts": player_with_gifts,
            "theif": theif,
        })
    context.update(default_context())
    return render(request, "core/active_game.html", context)


def game_details(request, code):
    status = GameSession.objects.get(code=code)
    if request.POST:
        if "open" in request.POST:
            game_player = GamePlayer.objects.get(id=request.POST['open'])
            print(game_player.possession)
            game_player.possession = True
            game_player.save()

            # get current player
            get_current_turn(status)
            status.theif = None
            status.save()
            return redirect('core:active_game', code)
        if "steal" in request.POST:
            game_player = GamePlayer.objects.get(id=request.POST['steal'])
            game_player.possession = True
            game_player.save()

            stolen_player = GamePlayer.objects.get(id=request.POST['steal_from'])
            stolen_player.possession = False
            stolen_player.save()

            get_current_turn(status)
            status.theif = game_player
            status.save()
            return redirect('core:active_game', code)

    response = {
        'ready': status.ready,
        'setup': status.setup,
    }
    if status.setup == True:
        player = GamePlayer.objects.get(id=request.session['player_id'])
        response.update({
            'player_turn': player.turn,
        })
    if status.ready == True:
        players = GamePlayer.objects.filter(session_id=status)
        current_player = players.get(turn=status.current_turn)
        player_gifts = players.filter(possession=True)
        player_with_gifts = {}
        for player in player_gifts:
            player_with_gifts.update({player.id:player.name})

        if status.theif:
            theif = status.theif.id
            theif_name = status.theif.name
        else:
            theif = None
            theif_name = None

        if 'current_player' not in request.session or request.session['current_player'] != current_player.name:
            request.session['current_player'] = current_player.name
            reload_page = True

core/templates/core/active_game.html
{% extends 'core/base.html' %}
{% load static %}

{% block title %}
<title>{{title}} - Game {{game.code}}</title>        
{% endblock title %}

{% block content %}
<div class='container text-center'>
    {% if game.ready == True %}
    <div id="game_status" class="mt-3 mb-2">
        <h4>Game has started!</h4>
    </div>    
    {% else %}
    <div id="game_status" class="mt-3 mb-2">
        <h4>Waiting for game to start</h4>
    </div>
    {% endif %}

    <div id="player_details" class="mb-4">
        <h3 id="current_player" class="title-string">
            {% if game.ready == True %}
                {% if current_player.id == session_id %}
                    Your turn!
                {% else %}
                    {{current_player.name|title}} is up!
                {% endif %}
            {% endif %}
        </h3>
        <h2 id="player_turn" class="fw-bold"></h2>
    </div>

    {% if request.user.is_authenticated %}
        {% include 'core/active_game_current_player.html' %}        
    {% else %}

        {% if current_player.id == session_id %}
            {% include 'core/active_game_current_player.html' %}
        {% else %}
        {% endif %}

    {% endif %}
</div>
{% endblock content %}

{% block javascript %}
{#<script src="{% static 'core/main.js' %}" async defer></script>#}
<script>
$(document).ready(function(){
    if("{{game.ready}}" == "True"){
        var interval = 1000
    }
    else {
        var interval = 10000
    }
    setInterval(function (){
        $.ajax({
            url: "{% url 'core:game_details' game.code %}",
            type: "GET",
            dataType: "json",
            success: function(data){
                console.log(data['setup'])
                console.log(data['ready'])
                console.log("current session id: ", data['session_player'])
                console.log(data['current_turn'])
                console.log(data['theif'])
                console.log("theif: ", data['theif_name'])
                console.log('current player name: ', data['current_player_name'])
                console.log('players with gifts count: ', data['players_with_gifts_len'])
                console.log('players with gifts list: ', data['players_with_gifts'])
                console.log('player_id: ', data["current_player_id"])
                console.log('player_turn: ', data["player_turn"])
                if(data['reload_page'] == true) {
                    location.reload()
                }
                if(data['setup'] == true && data['ready'] == false) {
                    $("#current_player").text("Your turn is")
                    $("#player_turn").text(data['player_turn'])
                }
                if(data['ready'] == true) {
                    if(data['session_player'] == data["current_player_id"]) {
                        if($('#active_player').length == 0){
                            if (data['theif']) {
                                window.navigator.vibrate(500);
                            }
                            location.reload()
                        }
                        else{
                            if (data['theif']) {
                                $("#player_turn").text("Your gift was stolen by " + data['theif_name'])
                            }
                            $("#current_player").text("Your turn!")
                        }
                    }
                    else{
                        $("#current_player").text(data['current_player_name'] + " is up!");
                        $("#player_turn").text("");
                    }
                }
            },
        });
    }, interval);
});
</script>
<script>
    /*
    $(".gift_action_form").submit(function (e) {
        // preventing from page reload and default actions
        e.preventDefault();
        // serialize the data for sending the form data.
        var serializedData = $(this).serialize();

        $.ajax({
            url: "{% url 'core:game_details' game.code %}",
            type: "POST",
            data: serializedData,
            success: function(data){
                console.log("Success! Next Players Turn")
            },
        })
    });
    */
</script>

{% endblock javascript %}

core/templates/core/active_game_current_player.html
<div id="active_player" class="mb-2">
    <form class="gift_action_form mb-1" method='POST' action="{% url 'core:game_details' game.code %}">
        {% csrf_token %}
        <input type="hidden" name="open" value="{{current_player.id}}">
        <button id="gift_open_submit" type="submit" class="btn btn-light mb-1">Open A Gift</button>
    </form>
        
    {# available gifts #}
    <span id="player_gifts" class="mb-1">
        {% for player in players_with_gifts.items %}
        {% if player.0 != theif %}
        <form class="gift_action_form mb-1" method="POST" action="{% url 'core:game_details' game.code %}">
            {% csrf_token %}
            <input type="hidden" name="steal" value="{{current_player.id}}">
            <input type="hidden" name="steal_from" value="{{player.0}}">
            <input id="gift_open_submit" class="btn btn-danger" type="submit" value="Steal from {{player.1|title}}">
        </form>
        {% endif %}
        {% endfor %}
    </span>
</div>

core/templates/core/base.html
{% load static %}

<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js"> <!--<![endif]-->
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        {% block title %}
        
        {% endblock title %}
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- jquery -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

        <!-- bootstrap 5-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

        <link rel="stylesheet" href="{% static 'core/main.css' %}?v=0.11">
    </head>
    <body>
        <!--[if lt IE 7]>
            <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="#">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->

        {% block content %}
        
        {% endblock content %}

        <script src="http://code.jquery.com/jquery-3.5.1.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>        {% block javascript %}

        {% endblock javascript %}
    </body>
</html>

core/templates/core/index.html
{% extends 'core/base.html' %}

{% block title %}
<title>{{title}}</title>        
{% endblock title %}

{% block content %}
<div class="container d-flex align-items-center justify-content-center vh-100 ">
    <div class="row w-100">
        <h1 class="text-center">Dirty Santa Game</h1>
        {% if error %}
            <p class="text-center">{{error}}</p>
            <p class="text-center">Code Entered: {{code}}</p>
        {% endif %}
        {% if current_game %}
            <form method="POST" class="text-center">
                {% csrf_token %}
                <input type="hidden" id="cont_game" name="continue" value="{{current_game}}">
                <button type="submit">Continue Game</button>
            </form>
            {% if request.user.is_authenticated %}
                <h4 class="text-center">You are logged in as {{request.user|title}}</h4>
                <h5 class="text-center"><a class="link-light" href="{% url 'admin:index' %}">Click here for Admin</a></h5>
                {% if cur_game_setup == False or cur_game_ready == False %}
                <form method="POST" class="text-center">
                    {% csrf_token %}
                    <input type="hidden" id="setup_game" name="setup" value="{{current_game}}">
                    <button type="submit">Continue Game Setup</button>
                </form>
                {% endif %}
            {% endif %}
        {% else %}
            {% if request.user.is_authenticated %}
            <h4 class="text-center">You are logged in as {{request.user|title}}</h4>
            <h5 class="text-center"><a class="link-light" href="{% url 'admin:index' %}">Click here for Admin</a></h5>
            <form method="POST" class="text-center">
                {% csrf_token %}
                <input type="hidden" id="new_game" name="new" value="new">
                <button type="submit">Start New Game</button>
            </form>
            {% else %}
            <form method="POST" class="text-center">
                {% csrf_token %}
                <input class="mb-1" type="text" name="join" placeholder="Game Code"><br>
                <input class="mb-1" type="text" name="name" placeholder="Your Name"><br>
                <button class="" type="submit">Join Game</button>
            </form>
            {% endif %}
        {% endif %}
    </div>
</div>
{% endblock content %}

core/templates/core/new_game.html
{% extends 'core/base.html' %}

{% block title %}
<title>{{title}} - Game Setup</title>        
{% endblock title %}

{% block content %}
<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <form method="POST">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Add New Player</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <p class="warning">Warning - Do not use this form to add any player who intends to use their phone.</p>
                        {% csrf_token %}
                        <input type="hidden" name="action" value="add_player">
                        <label for="new_name">Players Name: </label>
                        <input id="new_player_name" type="text" name="new_name">
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Add Player</button>
                </div>
            </form>
        </div>
    </div>
</div>

<div class="container text-center mt-3">
    {% if new_player %}
    <div class="alert alert-{{new_player_outcome}} alert-dismissible fade show" role="alert">
        <strong>{{new_player}}</strong> {{new_player_message}}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
    {% endif %}

    <h2>Game: {{game.code}}</h2>
    <h4>Total Players: {{player_count}}</h4>
    {# get game ready #}
 
    <button type="button" id="refresh_page" class="btn btn-light mb-1">Refresh</button>
    <form method="POST">
        {% csrf_token %}
        <input type="hidden" name="code" value="{{game.code}}">
        <input type="hidden" name="action" value="cancel">
        <button type="submit" class="btn btn-danger mb-1">Cancel Game</button>
    </form>

    {% if game.setup == False %}
    <form method="POST">
        {% csrf_token %}
        <input type="hidden" name="code" value="{{game.code}}">
        <input type="hidden" name="action" value="setup">
        <button type="submit" class="btn btn-info mb-1">Setup Game</button>
    </form>
    {% else %}
    <form method="POST">
        {% csrf_token %}
        <input type="hidden" name="code" value="{{game.code}}">
        <input type="hidden" name="action" value="ready">
        <button type="submit" class="btn btn-success mb-1">Ready Game</button>
    </form>
    {% endif %}
    
    <!-- Button trigger modal -->
    <button type="button" class="btn btn-primary mb-1" data-bs-toggle="modal" data-bs-target="#exampleModal">
        Add Player
    </button>
    

    {% for player in players %}
    <h3>{{player.name|title}} - Turn: <strong>{{player.turn}}</strong></h3>
    {% endfor %}

</div> 
{% endblock content %}

{% block javascript %}
<script>
    var myModal = document.getElementById('exampleModal')
    var myInput = document.getElementById('new_player_name')
    
    myModal.addEventListener('shown.bs.modal', function () {
      myInput.focus()
    })
</script>
<script>
    $('#refresh_page').click(function(){
        location.reload()
    })

</script>
{% endblock javascript %}